### PR TITLE
cmd/govim: append working dir as PWD when calling go env GOMOD

### LINKED ISSUE #1035: cmd/govim: file watching doesn't work in macOS temp directories
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  4 2021 21:55:13)
macOS version - x86_64
Included patches: 1-2465
Compiled by leitzler@calcium
Huge version without GUI.  Features included (+) or not (-):
+acl               +clipboard         -dnd               -gettext           +listcmds          -mouse_sysmouse    +postscript        +spell             +textobjects       +wildignore
+arabic            +cmdline_compl     -ebcdic            -hangul_input      +localmap          +mouse_urxvt       +printer           +startuptime       +textprop          +wildmenu
+autocmd           +cmdline_hist      +emacs_tags        +iconv             -lua               +mouse_xterm       +profile           +statusline        +timers            +windows
+autochdir         +cmdline_info      +eval              +insert_expand     +menu              +multi_byte        -python            -sun_workshop      +title             +writebackup
-autoservername    +comments          +ex_extra          +ipv6              +mksession         +multi_lang        -python3           +syntax            -toolbar           -X11
-balloon_eval      +conceal           +extra_search      +job               +modify_fname      -mzscheme          +quickfix          +tag_binary        +user_commands     -xfontset
+balloon_eval_term +cryptv            -farsi             +jumplist          +mouse             +netbeans_intg     +reltime           -tag_old_static    +vartabs           -xim
-browse            -cscope            +file_in_path      +keymap            -mouseshape        +num64             +rightleft         -tag_any_white     +vertsplit         -xpm
++builtin_terms    +cursorbind        +find_in_path      +lambda            +mouse_dec         +packages          -ruby              -tcl               +virtualedit       -xsmp
+byte_offset       +cursorshape       +float             +langmap           -mouse_gpm         +path_extra        +scrollbind        +termguicolors     +visual            -xterm_clipboard
+channel           +dialog_con        +folding           +libcall           -mouse_jsbterm     -perl              +signs             +terminal          +visualextra       -xterm_save
+cindent           +diff              -footer            +linebreak         +mouse_netterm     +persistent_undo   +smartindent       +terminfo          +viminfo
-clientserver      +digraphs          +fork()            +lispindent        +mouse_sgr         +popupwin          -sound             +termresponse      +vreplace
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -o vim -lm -lncurses -liconv -framework AppKit
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +ccb2e90688 Tue Jan 19 17:33:33 2021 +0000 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/leitzler/Library/Caches/go-build"
GOENV="/Users/leitzler/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/leitzler/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/leitzler/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/leitzler/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/leitzler/sdk/gotip/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel +ccb2e90688 Tue Jan 19 17:33:33 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/var/folders/j4/l2j99h6d5qd6knjlllql0bb80000gn/T/tmp.tvpSUJ9d/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j4/l2j99h6d5qd6knjlllql0bb80000gn/T/go-build716494932=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What version/commit of `govim` are you using?
Current main, 9b702de

### What did you do?

Create a module in a temp directory and open main.go that has an unresolved reference.
```
$ cd $(mktemp -d) && go mod init foo
$ cat > main.go <<EOF
package main

import "fmt"

func main() {
        fmt.Println(A)
}
EOF
$ vi main.go
```

In another terminal (same folder):
```
$ cat > a.go <<EOF
package main

const A = 1
EOF
```

### What did you expect to see?
The diagnostic disappear, since govim should pick up the new file via file watching and send a notification to gopls.

### What did you see instead?
The diagnostic didn't disappear.

### PR DESCRIPTION
**Pull request by leitzler**
The file watcher didn't work when opening a module located in the temp
directory on macOS (e.g. "cd $(mktemp -d)").

This happend since vim returned the real path, e.g.
"/private/var/folders/..." when calling getcwd(-1), but as exec.Command
works on macOS it returned the returned the symlinked path, e.g.
"/var/folders/...".

We now apply the same work around as x/tools where the working directory
is appended as $PWD before calling exec.Command so it actually use the
working directory supplied.

Fixes #1035

### CODE REVIEW

File: cmd/govim/main.go [hunk 1]
```diff
@@ -349,7 +349,17 @@ func goModPath(wd string) (string, error) {
 		return "", fmt.Errorf("failed to execute [%v] in %v: %v\n%s", strings.Join(cmd.Args, " "), wd, err, out)
 	}
 
-	return strings.TrimSpace(string(out)), nil
+	gomod := strings.TrimSpace(string(out))
+	base := filepath.Base(gomod)
+	dir := filepath.Dir(gomod)
+
+	// Follow symlinks for the directory to match what vim returns for getcwd().
```
Comment (myitcv) [inline cmd/govim/main.go:356]: Small nit, but the change here could sit within `newModWatcher` couldn't/shouldn't it? Because _that's_ the place where symlinks are not followed. i.e. we have to have evaluated symlinks prior to creating the watcher, else we would need to configure a watching that follows symlinks (which we might want to do in any case?)

**Review by myitcv — APPROVED** [review]
LGTM with one thought/comment.

File: cmd/govim/main.go (hunk 1 above)
Comment (leitzler) [reply cmd/govim/main.go]: Your comment made me think about this another round since it is actually the inconsistence between vim's `getcwd()` and what `go env GOMOD` returns.

Turns out that it is `exec.Command` that won't use provided `cmd.Dir` if it points to the same dir as `$PWD`, even if one is the "real path" and the other is sym-linked.

Heschi pointed out in #tools that [x/tools handle this](https://github.com/golang/tools/blob/fe37c9e135b934191089b245ac29325091462508/internal/gocommand/invoke.go#L208) by adding `$PWD` so I went for that solution here as well. Then we'll get the same behaviour as gopls.

**Comment by myitcv** [comment]
I think the commit message title needs updating?

**Comment by leitzler** [comment]
Ops, forgot the topic when I updated, thanks!
