### PR TITLE
cmd/govim: fix shutdown sequence

### LINKED ISSUE #842: cmd/govim: ensure that Shutdown() gets called on Vim shutdown
When exiting Vim, we do not trigger a shutdown within `govim`; we simply close the channel and then exit Vim without waiting for `govim` to complete its shutdown. We are, therefore, not guaranteed that the `*cmd/govim/govimplugin.Shutdown` method actually runs when Vim exits. Hence any temporary files/directories that we (or another process) have created might not actually get removed. 

We should trigger a proper shutdown sequence from Vim that ultimately calls this method before closing the channel; this is a similar protocol to that used in LSP.

Until we implement this, junk will likely be left lying around in `$TMPDIR`

### LINKED ISSUE #1059: cmd/govim: create temporary files within a govim-specific $TMP sub-directory
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 09 2021 23:51:55)
Included patches: 1-2489
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl/dyn
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim -lm -ltinfo -lelf -lacl -lattr -lgpm -ldl -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm
</pre></details>

### What version of Go are you using (`go version`)?

<details><summary>Go version</summary><br><pre>
$ go version
go version go1.16 linux/amd64
</pre></details>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gautam/.cache/go-build"
GOENV="/home/gautam/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/gautam/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gautam/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2665515259=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What version/commit of `govim` are you using?
a8b8ff21e5a8e67a4f251e7d4d6d67c7a49b5a43

### What is the output of `:messages` in Vim?
nothing afaict.

### Do the Vim channel, `govim` or `gopls` log files show anything interesting?

I haven't looked into any of them.

### How did you install `govim`?

vundle

### What did you do?

just used it :)

### What did you expect to see?
My `/tmp` directory remaining uncluttered.<br>
A few files generated by the plugin would be acceptable, a single directory created by the plugin (with all its temporary files placed inside) would be ideal.

### What did you see instead?
A whole bunch of `govim*`, `gopls*` & `vim_channel*` files.

### PR DESCRIPTION
**Pull request by myitcv**

### CODE REVIEW

File: cmd/govim/main.go [hunk 1]
```diff
@@ -217,14 +220,19 @@ type govimplugin struct {
...
 	if goplsEnv == nil {
 		goplsEnv = os.Environ()
 	}
+	// Match the logic within plugin/govim.vim
 	tmpDir := getEnvVal(goplsEnv, "TMPDIR")
 	if tmpDir == "" {
 		tmpDir = os.TempDir()
 	}
+	tmpDir = filepath.Join(tmpDir, "govim")
+	if err := os.MkdirAll(tmpDir, 0777); err != nil {
```
Comment (leitzler) [inline cmd/govim/main.go:233]: Wouldn't it make sense to create one per user? Otherwise we might end up with a `/tmp/govim` directory owned by me and permissions set to 755 where no other user can write. E.g. if I have `umask` set to `022`/`0022` (common default value).

File: plugin/govim.vim [hunk 2]
```diff
@@ -22,10 +22,18 @@ if has("patch-8.2.0452") && !has("patch-8.2.0466")
...
 
 " TODO: we are ignoring windows right now....
+" s:tmpdir is the root temporary directory within
+" which we will create a govim directory to contain
+" logfiles
 let s:tmpdir = $TMPDIR
 if s:tmpdir == ""
   let s:tmpdir = "/tmp"
 endif
+let s:tmpdir .= "/govim"
```
Comment (leitzler) [inline plugin/govim.vim:32]: same about UID here

**Review by leitzler — APPROVED** [review]
LGTM with two comments

File: cmd/govim/main.go (hunk 1 above)
Comment (myitcv) [reply cmd/govim/main.go:233]: Goodness me, despite our conversation about `/run/$UID/...` I completely forgot about this. Yes, you're absolutely right - we _have_ to create one per user. So that would end up looking like `$TMP/govim_$UID/...`. 

So now I'm left wondering whether a subdirectory is a better idea than hidden log files or not? 

BTW in my experience locally, the shutdown fixes resolve all of the tidying up issues for socket files.

Comment (myitcv) [reply cmd/govim/main.go]: I'm going to mark this conversation as resolved, and ask that we continue it over in #1063

File: plugin/govim.vim (hunk 2 above)
Comment (myitcv) [reply plugin/govim.vim]: Ditto.

**Comment by myitcv** [comment]
@leitzler - I've split out the socket/log file naming changes into #1063. Can you just confirm you're happy with this change as it stands?

**Comment by leitzler** [comment]
:+1:, good call
